# Generated by Django 2.2.2 on 2019-06-30 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Guarda la fecha de cuando se creó el registro', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Guarda la fecha de cuando se modificó el registro', verbose_name='modified at')),
                ('name', models.CharField(max_length=140, verbose_name='circle name')),
                ('slug_name', models.SlugField(max_length=140, unique=True)),
                ('about', models.CharField(max_length=255, verbose_name='cirlce description')),
                ('picture', models.ImageField(blank=True, upload_to='circles/pictures')),
                ('rides_taken', models.PositiveIntegerField(default=0)),
                ('rides_offered', models.PositiveIntegerField(default=0)),
                ('verified', models.BooleanField(default=False, help_text='Verificar usuarios de la comunidad', verbose_name='verified circle')),
                ('is_public', models.BooleanField(default=True, help_text='Saber si un circulo es publico o privado')),
                ('is_limited', models.BooleanField(default=False, help_text='Saber si el circle tiene limite de miembros', verbose_name='limited')),
                ('members_limit', models.PositiveIntegerField(default=0, help_text='Numero limite de miembros de un circle')),
            ],
            options={
                'ordering': ['-rides_taken', '-rides_offered'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
